=== TATJavaArturBarkou/TAT_JAVA_Barkou_Task4/parsersAndMarshalling/src/resources/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.barkou.com/command"
	xmlns:tns="http://www.barkou.com/command">

	<element name="commands">

		<complexType>

			<sequence>
				<element name="command" type="string" maxOccurs="20"/>
			</sequence>

		</complexType>

	</element>
</schema>

=== TATJavaArturBarkou/TAT_JAVA_Barkou_Task4/reflectionTask/src/resources/commands_list.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xml>


<tc:commands xmlns:tc="http://www.barkou.com/command"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.barkou.com/command schema.xsd">

	<command>AddAdminRights</command>
	<command>AddBook</command>
	<command>GetAllAvailableBooks</command>
	<command>GetAvailableBook</command>
	<command>GetUser</command>
	<command>OrderBook</command>
	<command>SetUserBanned</command>
	<command>ShowProfile</command>
	<command>SignIn</command>
	<command>SignOut</command>
	<command>SignUp</command>
	<command>UpdateBook</command>
	<command>UpdateProfile</command>
	<command>WrongRequest</command>

</tc:commands>
